<?xml version="1.0" encoding="utf-8"?>
<Database Name="dbb7ab6d80ef0b40bc925da0210152b17d" Class="hioDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=b7ab6d80-ef0b-40bc-925d-a0210152b17d.sqlserver.sequelizer.com;Initial Catalog=dbb7ab6d80ef0b40bc925da0210152b17d;User ID=wnohangthtsmleuv" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dbb7ab6d80ef0b40bc925da0210152b17dConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Lat" Type="System.Decimal" DbType="Decimal(18,8)" CanBeNull="true" />
      <Column Name="Long" Type="System.Decimal" DbType="Decimal(18,8)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_comment" Member="comments" ThisKey="UserID" OtherKey="UserID" Type="comment" />
      <Association Name="User_hio_event" Member="hio_events" ThisKey="UserID" OtherKey="UserID" Type="hio_event" />
      <Association Name="User_user_location" Member="user_locations" ThisKey="UserID" OtherKey="UserID" Type="user_location" />
    </Type>
  </Table>
  <Table Name="dbo.comments" Member="comments">
    <Type Name="comment">
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Member="Comment1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_comment" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="place_comment" Member="place" ThisKey="PlaceID" OtherKey="PID" Type="place" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.hio_events" Member="hio_events">
    <Type Name="hio_event">
      <Column Name="EID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Event" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_hio_event" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.notices" Member="notices">
    <Type Name="notice">
      <Column Name="NID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ann_content" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.user_locations" Member="user_locations">
    <Type Name="user_location">
      <Column Name="LID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LatVal" Type="System.Decimal" DbType="Decimal(18,8)" CanBeNull="true" />
      <Column Name="LongVal" Type="System.Decimal" DbType="Decimal(18,8)" CanBeNull="true" />
      <Column Name="Inuse" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_user_location" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="APIcalls" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="showTwitter" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="set1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="set2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="set3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.places" Member="places">
    <Type Name="place">
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LatVal" Type="System.Decimal" DbType="Decimal(18,8) NOT NULL" CanBeNull="false" />
      <Column Name="LongVal" Type="System.Decimal" DbType="Decimal(18,8) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Flag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Town" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="place_comment" Member="comments" ThisKey="PID" OtherKey="PlaceID" Type="comment" />
    </Type>
  </Table>
</Database>